// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzdoopavteiivbfjaelh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6ZG9vcGF2dGVpaXZiZmphZWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzM1NjMsImV4cCI6MjA3MTEwOTU2M30.IE0pX51ufqPTWcFagOQUcN530HpbSnB7IeHRvjAD11o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});